sudo: false

language: node_js
node_js:
  - iojs

git:
  # contributors task: need all commits until we cache contributions somewhere else https://github.com/putaindecode/putaindecode.fr/issues/218
  depth: 100000

notifications:
  irc:
    channels: "irc.freenode.org#putaindecode"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
  webhooks:
    - https://webhooks.gitter.im/e/f9058b60ad04e03a490e

install:
  - npm install --loglevel info

before_script:
  # for headless browsers
  # http://docs.travis-ci.com/user/gui-and-headless-browsers/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # gh-pages: because of how gulp-gh-pages works (with a clone), --global is required
  - git config --global user.name "Travis-CI"
  - git config --global user.email "mail+travis@putaindecode.fr"

script:
  - npm test
  # deploy real master only
  #- if [ $TRAVIS_PULL_REQUEST = "false" ] && [ $TRAVIS_BRANCH = "master" ]; then npm run _deploy; fi
  - npm run _deploy

env:
  global:
    # GH_TOKEN
    - secure: ghMMp0kKWiZvqhHDROxGPQOARnIYJIeZcu0RVgVHkNNFOeSoJg9X+zBfDn6plQyo59ogKisdyVJgSh7IS+HiF98lhEm3qHd4Cbs136m5Wz0FjhIbFsaFij2OT5ECco+sAkgqniv3rl+5IZMvDlMh8g0+jkhVRvpF3I/ye0ckMXo=
