# http://www.appveyor.com/docs/appveyor-yml
environment:
  nodejs_version: '10'

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

test_script:
  - node --version
  - yarn --version
  - yarn test

cache:
  - node_modules -> package.json

version: "{build}"
build: off
deploy: off
matrix:
  fast_finish: true
