[build]
  publish = "build"
  command = "yarn prerender"

[build.environment]
  NODE_VERSION = "10"
  YARN_VERSION = "1.12.3"
  YARN_FLAGS = "--pure-lockfile"

# GITHUB_TOKEN for API request is defined in Netlify UI
